apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: i2uox84up-python 
  janus-idp.io/tekton: i2uox84up-python
  backstage.io/kubernetes-id: i2uox84up-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: i2uox84up-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  